export const SET_ITEM = 'SET_ITEM'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'
export const LOGOUT_USER = 'LOGOUT_USER'

export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE'
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS'
export const FETCH_USER_PROFILE_FAIL = 'FETCH_USER_PROFILE_FAIL'

export const SET_USER_PROFILE = 'SET_USER_PROFILE'
export const SET_USER_PROFILE_SUCCESS = 'SET_USER_PROFILE_SUCCESS'
export const SET_USER_PROFILE_FAIL = 'SET_USER_PROFILE_FAIL'